name: Deploy for DigitalMall


on:
  push:
    baranches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18

    - name: Install dependencies
      run: npm install

    - name: Run test
      run: npm test

    - name: Login
      run: docker login -u bamdadn -p Nn@123456
    - name: build
      run: docker build -t digitalmall/backend:v1
    - name: Push
      run: docker push digitalmall/backend:v1

  deploy:    

     runs-on: ubuntu-latest
     needs: build

     steps: 
     - name: connect to k8s cluster
       run: | 
         mkdir -p ~/.kube
         echo "${{ secret.KUBE_CONFIG }}" > ~/.kube/config
         
