name: Backend and MongoDB CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Docker Image
        run: docker build -t $DOCKER_USERNAME/backend:${{ github.sha }} ./backend

      - name: Push Backend Docker Image
        run: docker push $DOCKER_USERNAME/backend:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      
      - name: Configure kubectl for DigitalOcean
        run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy MongoDB to DigitalOcean Kubernetes
        run: |
          kubectl apply -f k8s-manifests/mongodb-deployment.yaml

      - name: Apply Kubernetes Secrets for MongoDB
        run: |
          kubectl create secret generic app-secrets \
          --from-literal=mongo-root-username=${{ secrets.MONGO_INITDB_ROOT_USERNAME }} \
          --from-literal=mongo-root-password=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }} \
          --from-literal=mongo-username=${{ secrets.MONGO_USERNAME }} \
          --from-literal=mongo-password=${{ secrets.MONGO_PASSWORD }} \
          --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy Backend to DigitalOcean Kubernetes
        run: |
          kubectl set image deployment/backend backend=$DOCKER_USERNAME/backend:${{ github.sha }}
          kubectl rollout restart deployment/backend
